spring:
  application:
    name: index-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/vcaml/SpringConfigfile.git
          username: 734886783@qq.com
          password: 7717vcaml
          searchPaths: respo
       #   skip-ssl-validation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 2000
