spring:
  application:
    name: index-config-server
  cloud:
    config:
      server:
       git:
        uri: https://gitee.com/zhangqiang7717/trend-config
        searchPaths: respo
        username: zhangqiang7717
        password: 7717vcaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


